version: '3'

services:
  web-streamlit:
    image: producao-volatex
    build: https://github.com/kanyesteves/producao-volatex.git#master
    container_name: web
    networks:
      - volatex
    depends_on:
      - api-fastapi
    ports:
      - "8001:8001"
    links:
      - api-fastapi:fastapi
    restart: always
  api-fastapi:
    image: fastapi-volatex
    build: https://github.com/kanyesteves/fastapi-volatex.git#master
    container_name: api
    networks:
      - volatex
    expose:
      - "8000"

networks:
  volatex:
    driver: bridge
